### ISSUE TITLE
Bump npm to newest version

### ISSUE THREAD

**Issue by montanaflynn** [Fooidge/PleaseJS#44]
Version 0.2.0 doesn't support node and that's what is currently in npm.

```
/dev/colors/node_modules/pleasejs/please.js:600
})( window );
^
ReferenceError: window is not defined
at Object.<anonymous> (/dev/colors/node_modules/pleasejs/please.js:600:5)
```

Also 0.4.0 has a bug:

```
npm install
pleasejs@0.4.0 node_modules/pleasejs

node index.js
module.js:333
    throw err;
          ^
Error: Cannot find module 'pleasejs'
    at Function.Module._resolveFilename (module.js:331:15)
```

**Comment by Fooidge** [comment]
Thank you. Merged your pull. And honestly didn't know I had to republish each time I patched. Will from now on.
